featuredProjects:
  - lean-growth-website-design
  - alternative-investment-liquidity-dashboard
  - bikearn-move-to-earn-app
  - chacha-charity-on-chain-mobile-app
  - freelancer-job-finder-in-web3
  - social-media-for-dating
  - pockword-the-mobile-vocabulary-builder-app
  - custodial-wallets-website-dashboard
  - foreign-language-learning-app
  - dex-trading-platform-application
