featuredProjects:
  - lean-growth-website-design
  - custodial-wallets-website-dashboard
  - chacha-charity-on-chain-mobile-app
  - freelancer-job-finder-in-web3
  - dex-trading-platform-application
  - social-media-for-dating
  - bikearn-move-to-earn-app
  - pockword-the-mobile-vocabulary-builder-app
  - foreign-language-learning-app
